# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'myagentpool'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/Hemanth5588/maven_java.git'
- task: Bash@3
  inputs:
    targetType: inline
    script: 'cd 1/s/;mvn package'
- task: Bash@3
  inputs:
    targetType: inline
    script: |
      cat > dockerfile <<EOF
      FROM tomee
      COPY webapp/target/webapp.war /usr/local/tomee/webapps/testapp.war
      EOF
- task: Bash@3
  inputs:
    targetType: inline
    script: 'docker build -t myapp .'